all:
	xcodebuild -configuration Development
	ditto build/Development/DialerBundle.bundle ../SBook51/build/Development/SBook5.app/Contents/PlugIns/DialerBundle.bundle

clean:
	xcodebuild clean -buildstyle Development

